# Generated by Django 5.2.4 on 2025-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="name_VOI",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
