# Generated by Django 5.2.4 on 2025-08-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0002_submission_name_voi"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedform",
            name="name",
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
