# Generated by Django 5.2.4 on 2025-08-25 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submit", "0003_submittedform_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("R", "Running"),
                            ("F", "Failed"),
                            ("S", "Success"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[("N", "Numbering"), ("I", "CalculatingInterations")],
                        max_length=1,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submit.submission",
                    ),
                ),
            ],
        ),
    ]
