# Generated by Django 5.2.4 on 2025-08-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0004_submissiontask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiontask",
            name="task",
            field=models.CharField(
                choices=[("N", "Numbering"), ("I", "Calculating interactions")],
                max_length=1,
            ),
        ),
    ]
