# Generated by Django 5.2.4 on 2025-08-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0005_alter_submissiontask_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submissiontask",
            old_name="task",
            new_name="task_type",
        ),
    ]
