# Generated by Django 5.2.4 on 2025-08-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ligand_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPCRdbResidueAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uniprot_identifier", models.CharField(max_length=12)),
                ("response_json", models.JSONField()),
            ],
        ),
    ]
